import { test, expect, _electron as electron } from '@playwright/test';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';

test('keyboard help is contextual and readonly, with exclusive utilities and predictable focus', async () => {
  const profile = await fs.mkdtemp(path.join(os.tmpdir(), 'clip-utilities-'));
  const env: NodeJS.ProcessEnv = { ...process.env, CLIP_SANDBOX_E2E: '1' };
  delete env.ELECTRON_RUN_AS_NODE;
  const app = await electron.launch({ args: ['.', `--user-data-dir=${profile}`], env });
  try {
    const page = await app.firstWindow();
    await page.evaluate(async folder => { await (window as any).clipSandboxDesktop.__testSetNextFolderPath(folder); }, path.resolve('tests/e2e/fixtures/video-edit/clips'));
    await page.locator('#pickBtn').click();
    await expect(page.locator('#grid .thumb')).toHaveCount(2);
    await page.locator('#grid .thumb').first().click();
    await expect(page.locator('#toolbar .hint')).toHaveCount(0);
    const bounds = await page.locator('#centralWorkspace').boundingBox();
    await page.locator('#keyboardMapBtn').focus();
    await page.keyboard.press('Enter');
    await expect(page.locator('#keyboardMapHeading')).toBeFocused();
    await expect(page.locator('.keyboard-context')).toContainText('Collection');
    await expect(page.locator('#keyboardMapPanel')).toContainText('Global');
    await expect(page.locator('#keyboardMapPanel input, #keyboardMapPanel [contenteditable]')).toHaveCount(0);
    await expect(page.locator('#keyboardMapPanel button')).toHaveCount(1);
    await expect(page.getByRole('button', { name: 'Close Keyboard shortcuts', exact: true })).toBeVisible();
    await expect(page.locator('#keyboardMapPanel kbd')).toHaveCount(10);
    expect(await page.locator('#centralWorkspace').boundingBox()).toEqual(bounds);
    await page.keyboard.press('f');
    await page.keyboard.press('Delete');
    await expect(page.locator('#grid .thumb')).toHaveCount(2);
    await expect(page.locator('#deleteFromDiskDialog')).not.toBeVisible();
    await expect(page.locator('#globalAppBar')).toBeVisible();
    await page.screenshot({ path: 'test-results/keyboard-map-collection.png', animations: 'disabled' });
    await page.keyboard.press('Tab');
    await expect(page.getByRole('button', { name: 'Close Keyboard shortcuts', exact: true })).toBeFocused();
    await page.keyboard.press('Enter');
    await expect(page.locator('#globalUtilityHost')).toBeHidden();
    await expect(page.locator('#keyboardMapBtn')).toBeFocused();
    await page.locator('#keyboardMapBtn').click();
    await page.locator('#activityIndicatorBtn').click();
    await expect(page.getByRole('region', { name: 'Activity history' })).toBeFocused();
    await expect(page.locator('#keyboardMapBtn')).toHaveAttribute('aria-expanded', 'false');
    await expect(page.locator('#globalUtilityHost > section:visible')).toHaveCount(1);
    await page.keyboard.press('Escape');
    await expect(page.locator('#activityIndicatorBtn')).toBeFocused();
    await page.keyboard.press('Enter');
    await expect(page.locator('#activityIndicatorPanel')).toBeVisible();
    await page.getByRole('button', { name: 'Close Activity and Errors', exact: true }).click();
    await expect(page.locator('#globalUtilityHost')).toBeHidden();
    await expect(page.locator('#activityIndicatorBtn')).toBeFocused();
    await page.locator('#keyboardMapBtn').click();
    await page.keyboard.press('Escape');
    await page.keyboard.press('Enter');
    await expect(page.locator('#keyboardMapHeading')).toBeFocused();
    await page.locator('#settingsBtn').click();
    await expect(page.locator('#globalUtilityHost')).toBeHidden();
    await page.locator('#keyboardMapBtn').click();
    await expect(page.locator('.keyboard-context')).toContainText('Settings');
    await expect(page.locator('#keyboardMapPanel')).toContainText('No screen-specific shortcuts.');
    await expect(page.locator('#keyboardMapPanel kbd')).toHaveCount(1);
    await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setContentSize(900, 650));
    await expect(page.locator('#globalUtilityHost')).toBeInViewport();
    await page.screenshot({ path: 'test-results/keyboard-map-settings.png', animations: 'disabled' });
    await page.locator('#choosePipelinesRoot').focus();
    await expect(page.locator('#globalUtilityHost')).toBeHidden();
    await expect(page.locator('#choosePipelinesRoot')).toBeFocused();
    await page.locator('#appScreenSelector').selectOption('collection');
    await page.locator('#keyboardMapBtn').click();
    await page.keyboard.press('End');
    await expect(page.locator('#keyboardMapPanel h3').filter({ hasText: 'Global' })).toBeInViewport();
    await page.keyboard.press('Escape');
    await expect(page.locator('#keyboardMapBtn')).toBeFocused();
  } finally {
    await app.close();
    await fs.rm(profile, { recursive: true, force: true });
  }
});
